### ISSUE TITLE
PAINT_001  Drawing tool chooser

### ISSUE THREAD

**Issue by amix73** [sw19-tug/afternoon04#1]
Acceptance Criteria:
-) there must be an image-button or icon in the toolbar indicating the tool chooser
-) when tapping this tool-chooser button/icon a bottom-sheet containing the available tools to choose from is scrolled into view.
-) a tap on one of the tools chooses this tool for later painting actions

Description:
As a user I want to choose amongst the drawing tools - point, line, fill, eraser, circle, rectangle by tapping on a tool icon.

**Comment by MasaruKondera** [comment]
Feature finished.
