### ISSUE TITLE
PAINT_007_001 testSeekbarShowsTextBoxValue() should fail but succeeded

### ISSUE THREAD

**Issue by Yarmek** [sw19-tug/afternoon04#19]
Tested with wrong values to make it fail, but still succeeded the test. 
Commit: dc68a846de2c4ea204086b6b22a1973fb91d93d1

**Comment by amemisev** [comment]
solved!

changed to the function .check of View

onView(withId(R.id.color_picker_seekbar_red)).check(matches(withProgress(0)));
