### ISSUE TITLE
PAINT_018 Save result

### ISSUE THREAD

**Issue by uwe-h** [sw19-tug/afternoon04#53]
Acceptance Criteria:
-) If I press the save button, I would like to have opened a new window hwere I can select the path.
-) The photo should be saved in the selected path on my device.

Description:
As a user, I want to save a painting on a device.

Estimated story points: 3

**Comment by anhaupt** [comment]
File root = Environment.getExternalStorageDirectory();
                File file = new File(root.getAbsolutePath()+"/DCIM/Camera/img.jpg");
                try 
                {
                    file.createNewFile();
                    FileOutputStream ostream = new FileOutputStream(file);
                    bitmap.compress(CompressFormat.JPEG, 100, ostream);
                    ostream.close();
                } 
                catch (Exception e) 
                {
                    e.printStackTrace();
                }

**Comment by haubitzer** [comment]
PR

**Comment by Yarmek** [comment]
merged with #71
