### ISSUE TITLE
PAINT_024 Color Picker crash when tilting phone

### ISSUE THREAD

**Issue by Yarmek** [sw19-tug/afternoon04#62]
When the color picker is open and you rotate the phone, the color picker crashes and closes, app still runs afterwards. 

Error Message: 

> MainActivity has leaked window DecorView@ef5e202[] that was originally added here
Dialog.java: 316 in feature/PAINT_006

**Comment by haubitzer** [comment]
done

**Comment by MasaruKondera** [comment]
fixed & merged with #71
