### ISSUE TITLE
PAINT_035 Testcase for FillBucket fail when all testcases get tested

### ISSUE THREAD

**Issue by MasaruKondera** [sw19-tug/afternoon04#89]
When all testcases get tested, the fillbucket test cases fail due to a changed canvas.

When tested alone, all fill bucket tests work without any problems at all.

Suggesting: Implementing a general "clean canvas" for all testcases which resets the canvas each time so we can use a clean canvas every time we have to test it.

**Comment by Yarmek** [comment]
fixed with #94
